# Site settings
title: Austin Adams
description: Portfolio Website Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "AustinJAdams.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Austin Adams
user_description: I am an Economics and Mathematics student turned Statistics focused, attempting to leverage both Economics's ability to put data into context and Math's ability to take it out. My research is in asset pricing theory, using modern statistics techniques to more accurately and quickly price assets. Looking for Quantitative Finance or Data Science jobs after I graduate in January 2020. 
user_title: Mathematics and Economics Major at the University of Kansas
email: austin@ajadams.co
# twitter_username: lorem_ipsum
github_username:  AustinJAdams
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-143245770-1"

exclude: ['package.json', 'src' , 'node_modules']
