# Site settings
title: Austin Adams
description: Portfolio Website Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "AustinJAdams.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Austin Adams
user_description: I am an economics and mathematics student focusing in statistics. Implementing these skills, I leverage both economics’ ability to put data into context and math’s ability to take it out. My research focuses on pricing assets. Using modern statistics and computer science techniques, I create avenues to price them more quickly and accurately than with traditional methods. I am searching for quantitative finance or data science jobs after I graduate in January 2020. Reach out to me at me@ajadams.co or utilize my contact link down below.
user_title: Mathematics and Economics Major at the University of Kansas
email: austin@ajadams.co
# twitter_username: lorem_ipsum
github_username:  AustinJAdams
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-143245770-1"

exclude: ['package.json', 'src' , 'node_modules']
