# Site settings
title: Austin Adams
description: Portfolio Website Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "AustinJAdams.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Austin Adams
user_description: I am an economics and mathematics student focusing in statistics. Implementing these skills, I leverage both economics’ ability to put data into context and math’s ability to take it out. My current research focuses on pricing assets. I am currently preparing for my upcoming role at the Federal Reserve Board.
user_title: Global Capital Markets Research Assistant at the Federal Reserve Board
email: me@ajadams.co
# twitter_username: lorem_ipsum
github_username:  AustinJAdams
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-143245770-1"

exclude: ['package.json', 'src' , 'node_modules']
