# Site settings
title: Austin Adams
description: Portfolio Website Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "AustinJAdams.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Austin Adams
user_description: I am an economics and mathematics student turned statistics focused, attempting to leverage both economics' ability to put data into context and math's ability to take it out. My research is in pricing assets, using modern statistics and computer science techniques to more accurately and quickly price them. Looking for quantitative finance or data science jobs after I graduate in January 2020. Reach out to me at me@adams.co or my contact link down below. 
user_title: Mathematics and Economics Major at the University of Kansas
email: austin@ajadams.co
# twitter_username: lorem_ipsum
github_username:  AustinJAdams
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-143245770-1"

exclude: ['package.json', 'src' , 'node_modules']
